#!/usr/bin/env bash

PROGRAM=$(basename "$0")
PROGRAM_PATH=$(dirname "$0")
CONFIG_PATH="${PROGRAM_PATH}/config"
OLD_IFS=${IFS}

LANGUAGES=(de-de en-asia en-au en-ca en-gb en-ie en-sg en-us es-es es-us fr-ca fr-fr it-it pl-pl pt-pt)
OVERWRITE_SUBS='de en es fr it pl pt'
OVERWRITE_MODE=body

MANAGER=(
  "DE-DE::https://www.ovh.com/auth/?action=gotomanager\&from=https://www.ovh.de/\&ovhSubsidiary=de"
  "EN-ASIA::https://ca.ovh.com/auth/?action=gotomanager\&from=https://www.ovh.com/asia/\&ovhSubsidiary=asia"
  "EN-AU::https://ca.ovh.com/auth/?action=gotomanager\&from=https://www.ovh.com.au/\&ovhSubsidiary=au"
  "EN-CA::https://ca.ovh.com/auth/?action=gotomanager\&from=https://www.ovh.com/ca/en/\&ovhSubsidiary=ca"
  "EN-GB::https://www.ovh.com/auth/?action=gotomanager\&from=https://www.ovh.co.uk/\&ovhSubsidiary=GB"
  "EN-IE::https://www.ovh.com/auth/?action=gotomanager\&from=https://www.ovh.ie/\&ovhSubsidiary=ie"
  "EN-SG::https://ca.ovh.com/auth/?action=gotomanager\&from=https://www.ovh.com/sg/\&ovhSubsidiary=sg"
  "EN-US::https://ca.ovh.com/auth/?action=gotomanager\&from=https://www.ovh.com/world/\&ovhSubsidiary=we"
  "ES-ES::https://www.ovh.com/auth/?action=gotomanager\&from=https://www.ovh.es/\&ovhSubsidiary=es"
  "ES-US::https://ca.ovh.com/auth/?action=gotomanager\&from=https://www.ovh.com/world/\&ovhSubsidiary=ws"
  "FR-CA::https://ca.ovh.com/auth/?action=gotomanager\&from=https://www.ovh.com/ca/fr/\&ovhSubsidiary=qc"
  "FR-FR::https://www.ovh.com/auth/?action=gotomanager\&from=https://www.ovh.com/fr/\&ovhSubsidiary=fr"
  "IT-IT::https://www.ovh.com/auth/?action=gotomanager\&from=https://www.ovh.it/\&ovhSubsidiary=it"
  "PL-PL::https://www.ovh.com/auth/?action=gotomanager\&from=https://www.ovh.pl/\&ovhSubsidiary=pl"
  "PT-PT::https://www.ovh.com/auth/?action=gotomanager\&from=https://www.ovh.pt/\&ovhSubsidiary=pt"
)
OVHCLOUD_LANG=(
  "DE-DE::de"
  "EN-ASIA::asia"
  "EN-AU::en-au"
  "EN-CA::en-ca"
  "EN-GB::en-gb"
  "EN-IE::en-ie"
  "EN-SG::en-sg"
  "EN-US::en"
  "ES-ES::es-es"
  "ES-US::es"
  "FR-CA::fr-ca"
  "FR-FR::fr"
  "IT-IT::it"
  "PL-PL::pl"
  "PT-PT::pt"
)
OVHDOCS_LANG=(
  "DE-DE::de"
  "EN-ASIA::asia/en"
  "EN-AU::au/en"
  "EN-CA::ca/en"
  "EN-GB::gb/en"
  "EN-IE::ie/en"
  "EN-SG::sg/en"
  "EN-US::us/en"
  "ES-ES::es"
  "ES-US::us/es"
  "FR-CA::ca/fr"
  "FR-FR::fr"
  "IT-IT::it"
  "PL-PL::pl"
  "PT-PT::pt"
)

update_link_subs(){
  for i in "${MANAGER[@]}";do
    if [[ "${i%%::*}" == "${GUIDE_SUB^^}" ]];then
      SEARCH="${i##*::}"
    fi
    if [[ "${i%%::*}" == "${LANG^^}" ]];then
      REPLACE="${i##*::}"
    fi
  done
  echo -e "MANAGER:\n * SEARCH ${SEARCH}\n * REPLACE ${REPLACE}"
  sed -i "s,${SEARCH},${REPLACE},g" ${TARGET}

  for i in "${OVHCLOUD_LANG[@]}";do
    if [[ "${i%%::*}" == "${GUIDE_SUB^^}" ]];then
      SEARCH="www.ovhcloud.com/${i##*::}"
    fi
    if [[ "${i%%::*}" == "${LANG^^}" ]];then
      REPLACE="www.ovhcloud.com/${i##*::}"
    fi
  done
  echo -e "OVHCLOUD_LANG:\n * SEARCH ${SEARCH}\n * REPLACE ${REPLACE}"
  sed -i "s,${SEARCH},${REPLACE},g" ${TARGET}

  for i in "${OVHDOCS_LANG[@]}";do
    if [[ "${i%%::*}" == "${GUIDE_SUB^^}" ]];then
      SEARCH="docs.ovh.com/${i##*::}"
    fi
    if [[ "${i%%::*}" == "${LANG^^}" ]];then
      REPLACE="docs.ovh.com/${i##*::}"
    fi
  done
  echo -e "OVHDOCS_LANG:\n * SEARCH ${SEARCH}\n * REPLACE ${REPLACE}"
  sed -i "s,${SEARCH},${REPLACE},g" ${TARGET}
}

git rev-parse --is-inside-work-tree > /dev/null
GIT_ROOT="$(git rev-parse --show-toplevel)"
cd "${GIT_ROOT}"

find "${GIT_ROOT}" -type f -name "duplicate.task" | while read tasks
do
  cat ${tasks} | while read task
  do
    GUIDE_SUB=$(echo ${task} | awk -F ":" '{print $1}')
    GUIDE_CONFIG=$(echo ${task} | awk -F ":" '{print $2}')
    GUIDE_OVERWRITE=$(echo ${task} | awk -F ":" '{print $3}')
    GUIDE=$(dirname ${tasks})/guide.${GUIDE_SUB}.md
    [[ -n ${GUIDE_CONFIG} ]] && source "${CONFIG_PATH}/${GUIDE_CONFIG}"
    [[ -n ${GUIDE_OVERWRITE} ]] && eval ${GUIDE_OVERWRITE}
    LANGUAGES=("${LANGUAGES[@]/$GUIDE_SUB}")
    for LANG in ${LANGUAGES[@]}
    do
      TARGET=$(dirname ${GUIDE})/guide.${LANG}.md
      echo "GUIDE: ${GUIDE#${GIT_ROOT}\/}"
      echo "TARGET: ${TARGET#${GIT_ROOT}\/}"
      if [[ -f ${TARGET} && ${OVERWRITE_MODE} == "body" && $(echo ${OVERWRITE_SUBS} | grep -ow "${LANG::2}" | wc -w) != 0 ]];then
        TARGET_FM=$(sed -n '1,/---/p' ${TARGET})
        sed -e '1,/---/d' ${GUIDE} > ${TARGET}
        update_link_subs && wait
        CONTENT=$(echo "${TARGET_FM}" && cat ${TARGET})
        echo "${CONTENT}" > ${TARGET}
        GUIDE_UPDATED_KEY=$(grep -Eo "^updated: [0-9]{4}(-[0-9]{2}){2}.+?$" ${GUIDE})
        TARGET_UPDATED_KEY=$(grep -Eo "^updated: [0-9]{4}(-[0-9]{2}){2}.+?$" ${TARGET})
        sed -i "2,/---/ s/${TARGET_UPDATED_KEY}/${GUIDE_UPDATED_KEY}/" ${TARGET}
      else
        cp -f ${GUIDE} ${TARGET}
        update_link_subs && wait
        if [[ "${GUIDE_SUB::2}" != "${LANG::2}" ]];then
          for i in "${OVHDOCS_LANG[@]}";do
            if [[ "${i%%::*}" == "${GUIDE_SUB^^}" ]];then
              CANONICAL_LANG="${i##*::}"
            fi
          done
          CANONICAL_URL="https://docs.ovh.com/${CANONICAL_LANG}/"
          IFS='/' read -r -a arr <<< $(dirname ${GUIDE#${GIT_ROOT}\/} | cut -d/ -f 3-)
          IFS=${OLD_IFS}
          p=$(echo ${GUIDE#${GIT_ROOT}\/} | awk -F "/" '{print $1"/"$2"/"}')
          for d in ${arr[@]}
          do
            p+=${d}/
            CANONICAL_URL+=$(cat ${p}*.${GUIDE_SUB}.md | sed -n '2,/---/p' | awk -F ": " '/^slug: / {print $2}'  | tr -d "\r")/
          done
          sed -i "2,/---/ s;---;routes:\n    canonical: '${CANONICAL_URL}'\n---;" ${TARGET}
          echo "CANONICAL_URL: ${CANONICAL_URL}"
        fi
      fi
      echo
    done
  done && wait
  rm -f ${tasks}
  echo
done
